### ISSUE TITLE
Lombok as compile-only dependencies

### ISSUE THREAD

**Issue by AHeise** [mguenther/kafka-junit#36]
Hi, I'm not entirely sure what the actual issue is but I can't seem to compile my project in intellij once I added your dependency to my test scope.
Googling showed that there may be a version hickup in lombok.

Since I haven't done maven in ages, I might have missed the point, but is lombok in your project a compile-only dependency? If not, could you please make a (SNAPSHOT) release with it as compile-only?

**Comment by mguenther** [comment]
Thank you for bringing this issue to my attention! This is indeed a problem, as the Lombok dependency is missing the scope 'provided', which would flag it as a compile-time-only dependency.

I'll release a bugfix soonish for the 2.1.x line. Do you use an older version of kafka-junit?

**Comment by mguenther** [comment]
Fixed the issue and released 2.1.1. This will take a couple of hours until it hits Maven Central. I'll file a release note as soon as it is available there. Please let me know if this fixes your particular issue.

**Comment by AHeise** [comment]
Thank you for the fast reaction! 

I'm using 2.1.0. I just started using (and loving it) and use it with kafka 2.2.0. I managed to get it running by explicitly removing the transitive lombok dependency.

**Comment by mguenther** [comment]
Thanks for the kind feedback, I appreciate it. I'm glad that you find kafka-junit useful :). Release 2.1.1 is available in Maven Central (see the release notes for [2.1.1](https://github.com/mguenther/kafka-junit/releases/tag/6a1232d)).
