### ISSUE TITLE
Increase Apache Kafka dependency to 2.4.x

### ISSUE THREAD

**Issue by Koriit** [mguenther/kafka-junit#39]
Kafka has recently released new 2.4.0 version.

When I update my kafka-clients library to 2.4.0 I'm getting `NoSuchFieldError` in the tests.

Thanks!

**Comment by mguenther** [comment]
Thanks for bringing this to my attention. The update to 2.4.0 will take a couple of days, especially during the holiday season.

**Comment by mguenther** [comment]
Blocked by #40.

**Comment by mguenther** [comment]
Upgraded Kafka dependencies successfully to 2.4.0 and released 2.4.0 of kafka-junit. This will take a couple of hours until it hits Maven Central. I'll file a release note along with a migration path as soon as it is available there.
