### ISSUE TITLE
jackson-databind 2.10 has been closed

### ISSUE THREAD

**Issue by julianladisch** [mguenther/kafka-junit#59]
jackson-databind 2.10 has been closed since 2021-09-30, doesn't get any updates and therefore can no longer been used in critical production code: https://github.com/FasterXML/jackson/wiki/Jackson-Releases

Trying to use a jackson-databind version >= 2.11 fails with this error message:

`Scala module 2.10.5 requires Jackson Databind version >= 2.10.0 and < 2.11.0`

Please change kafka-junit so that it can be used with latest jackson-databind versions. Thank you!

**Comment by mguenther** [comment]
This dependency is introduced with Apache Kafka and thus best addressed at the ASF issue tracker for Kafka.

**Comment by julianladisch** [comment]
Thank you releasing kafka-junit 3.0.0 that resolved this issue! It bumps Apache Kafka from 2.8.0 to 3.0.0 resulting in a jackson-databind bump from 2.10.5.1 to 2.12.3.
