### ISSUE TITLE
Risks of Running Version Higher Than Actual Cluster

### ISSUE THREAD

**Issue by ajameson-hbo** [mguenther/kafka-junit#63]
What sorts of risks is one taking by running a version of the library that's greater than the actual version of the Kafka cluster ? More recent versions of this library have a nicer api and that would be great to use. Does the library actually spin up a version of Kafka that is reflective of the library version? If so, can one use a more recent version of the library, but specifiy and earlier version of Kafka?

**Comment by mguenther** [comment]
In the days pre-0.10.0 the Kafka client library was not compatible with older versions of the broker. However, with the release of 0.10.2 and subsequent releases, Confluent seems to put a higher emphasis on both backward and forward compatibility of their libraries (see https://www.confluent.io/blog/upgrading-apache-kafka-clients-just-got-easier/). I haven't put this to the test, though.

Kafka for JUnit is not able to spin up a Kafka cluster in a desired version. The Kafka version used for an embedded broker and the Kafka clients library is fixed for a release of Kafka for JUnit (you might have noticed that the release schedule somewhat follows the Kafka release schedule). Of course, this has both an upside and a downside. The downside is that changes to the API as well as feature enhancements are released as soon as a new Kafka major/minor release is available. The upside is that this coupling limits the need to support a plethora of different versions of Apache Kafka per release of Kafka for JUnit, which would just not be feasible in terms of required time to manage all these dependencies and Kafka-side deprecations in between versions properly.

But, you can surely use Testcontainers in combination with Kafka for JUnit and rely on the forward compatibility that the Kafka clients library offers. That way, you'd use Testcontainers to spin up an external broker in the version that matches your production setup and use Kafka for JUnit to connect with it via the `ExternalKafkaCluster` abstraction. Given the promised 0-downtime-capability of the Kafka clients library, this should work.

Hope this helps.

**Comment by ajameson-hbo** [comment]
It does help. Thanks for the explanation.
