### ISSUE TITLE
Increase Apache Kafka dependency to 3.2.0

### ISSUE THREAD

**Issue by BenjaminBuick** [mguenther/kafka-junit#64]
Apache Kafka 3.2.0 was released on 9th of May 2022. 
We should support the new 3.2.0 release.

**Comment by mguenther** [comment]
Thank you Ben, your contribution is very much appreciated! There are no new  features planned for 3.2.0, so I already submitted the release of 3.2.0 including the version bump. It'll take a couple of hours until this hits Maven Central. I'll file a release note as soon as it is ready.
