### ISSUE TITLE
KafkaConfig$.MODULE$.PortProp() does no longer exist in 3.2.0

### ISSUE THREAD

**Issue by stinnux** [mguenther/kafka-junit#66]
Previously we used the property KafkaConfig$.MODULE$.PortProp() to set the port of the Kafka broker. 

This property does no longer exist in 3.2.0. How can we set the port now?

**Comment by mguenther** [comment]
From the official Kafka documentation:

> The port and host.name configurations were removed. Please use listeners instead.

Please have a look at the official documentation for anything related to configuring Apache Kafka (https://kafka.apache.org/documentation). Kafka for JUnit is able to use the full set of configuration parameters when configuring the cluster. If you need to change the `port` or `host.name` for your test setup, you should go along with the intended way of doing things as of Apache Kafka 3.2.0.

**Comment by stinnux** [comment]
Thanks for the info. I didn't look into the 3.0 release notes and therefore missed it.

Greetings from Riedstadt

**Comment by mguenther** [comment]
Sure, glad I could help!

> Greetings from Riedstadt

👋🏻
