### ISSUE TITLE
Using connectors, how do I know what triggers my connector code (not a bug)

### ISSUE THREAD

**Issue by cstmgl** [mguenther/kafka-junit#67]
Hi all, 
First of all thanks for this project it's really amazing, specially to me since I'm not a kafka expert this helps me a lot with the testing.
I'm upgrading my project version from 2.7 to 2.8 and somehow my junit tests stopped working.
I'm using a connect cluster almost as described here: https://mguenther.github.io/kafka-junit/#section:embedded-kafka-cluster

```
    this.kafkaCluster = provisionWith(newClusterConfig()
      .configure(brokers().withNumberOfBrokers(1))
      .configure(kafkaConnect().deployConnector(defaultJdbcConfiguration())));
```

But somehow my connector task never seems to be triggered and consume any records.
In the version 2.7 it seems it was working fine.

Just to give context, enabling debug, I can see the connect and connectors in my cluster variable, I can see the topics exist, the data in the topic if I do a simple readValues also works.

So my question is, how do I know or see what manages the triggering of the tasks as consumers.
In my case I'm using a SinkTask as consumer and I expected somehow to see in the EmbeddedKafkaCluster that the consumer would be registered there?

Just some more information, I do see in the log that the thread for my Task starts and I see the Config of my task being loaded, so I just don't understand why it seems to consume no data at all...

This is definitely not a bug but more of a question/discussion but I could not find how to open discussions.
Thanks for any feedback

**Comment by mguenther** [comment]
Thanks for the kind words, I appreciate your feedback!

Kafka for JUnit is not able to spy on deployed connectors. You have to treat these components as a black-box and check that the records they produce are in line with your expectation.

But the situation that you describe sounds indeed a bit strange. I do have a regression test that deploys a connector and checks that the connector is able to emit records into a target topic, so I guess the write-side of the whole thing is okay.

I'm not sure if I understand your setup correctly. You're deploying a connector that consumes records from another topic, does something with the consumed records and emits the results to another topic. That's basically it, right? And what you observe is, that the consumer that you start as part of the connector task is not able to read data?

Did you check that your particular configuration of the whole setup (brokers, consumers, producers, connectors) is still fine with Kafka 2.8.0?

**Comment by cstmgl** [comment]
Hi all, sorry for the delay in response.
In the end everything worked fine, I was missing one fundamental log that was showing me an error in my configuration.
Yes my setup is basically I have a "source" connector that is generator random data into kafka, not from a different topic, but really random and I was trying to then build a consumer for that random data and see it was working. 
It works fine but somehow I had missed that error in the config in the middle of all the threads
