### ISSUE TITLE
Scala 2.12 support

### ISSUE THREAD

**Issue by misinspire** [mguenther/kafka-junit#68]
I have an environment that runs with `Scala 2.12` dependencies. Upgrade is not possible to `Scala 2.13`. 

Hence I need my transitive dependencies to be `2.12` which is at the moment not available with `kafka-junit`.
There's support for `2.11` and `2.13`, but unfortunately the `2.11` is lacking support for Kafka version I have. 

I'll share a PR shortly.

**Comment by mguenther** [comment]
Thanks for bringing this to my attention! I can't simply merge your fix into the mainline of Kafka for Junit as this would introduce incompatibilities for all users that run on Scala 2.13. To be frank, I'm not quiet sure if I like the idea to maintain separate releases in the future (one for 2.13, one for 2.12). I'll see what I can do (I'll test the library with 2.12 first, but this will surely take a couple of days before I can get back to you).

**Comment by mguenther** [comment]
Sorry for the late response - but with holidays and all, some issues might linger longer than I'd like them to.

I actually don't like the added maintenance burden that having two separate artefacts for the same version of Kafka for JUnit would introduce. The default will be Scala 2.13. Did you check if excluding the Kafka dependencies for Scala 2.13 and adding the proper ones for Scala 2.12 does the job in your case?

**Comment by misinspire** [comment]
Yes, my case is solved when using Scala 2.12 dependencies. In the meanwhile I had to find other ways to move on with which works just fine for now. 

I could still go on with a fork on my end but hopefully that time will never come because of updating my environment to Scala 2.13. 

Thanks for looking into this and for this great lib! ❤️
