### ISSUE TITLE
kafka-junit library not  useful with KafkaListener interface and Kafkatemplate class ?

### ISSUE THREAD

**Issue by vaibhav-b** [mguenther/kafka-junit#73]
Hi @mguenther  @BenjaminBuick,

Hope you are doing well. 
I was evaluating testing library for kafka unit/integration testing  and found **kafka-junit**  library.

I feel beauty of this library is in-memory kafka cluster. 
Its starts in memory kafka-cluster which is really helpful to test scenario specific to cluster along kafkabroker/ producer/consumer etc...

Could you please provide Sample 2 test cases with kafka-junit for following scenario.

-- If we send some test data using  embeddedKafkaCluster.send(to("test-topic", "a", "b", "c")), which should trigger method link with KafkaListener
-- if we send test data using kafkatemplate.send("test-topic","data") then embeddedKafkaCluster.observe(on("test-topic", 1));

Could you please provide example of KafkaListener interface and Kafkatemplate class with kafka-junit library ?

**Comment by mguenther** [comment]
Hi there, 

please have a look at [Using Kafka for JUnit with Spring Kafka](https://www.mguenther.net/2021/03/using_kafka_for_junit_with_spring_kafka/index.html) and the GitHub Repository of  my [Spring Kafka Introduction](https://github.com/mguenther/spring-kafka-introduction).

This should get you started on how to write integration tests if conjunction with Spring Kafka components.

Cheers,
Markus

**Comment by mguenther** [comment]
I've opened a dedicated issue for incorporating the available documentation that is scattered across several resources into the user's guide of Kafka for JUnit. I consider this issue closed. For an update on the documentation part, please have a look at #82.

**Comment by vaibhav-b** [comment]
Thanks @mguenther for creating #82 . Hopefully centeralize documentation along with sample examples will be useful to adopt this library.

Cheers,
Vaibhav
