### ISSUE TITLE
Remove deprecated methods from the public API of Kafka for JUnit

### ISSUE THREAD

**Issue by mguenther** [mguenther/kafka-junit#74]
### 🆕🐥 First Timers Only

This issue is reserved for people who never contributed to Open Source before. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

### 👾 Description of the issue

Over the course of the last versions some of the methods for configuring an embedded Kafka broker changed to be more declarative. All methods that got replaced with a more aptly named one are marked as `@Deprecated`. Almost all of these deprecations were introduced with version 2.7.0 of Kafka for JUnit. This version has been released on January 4th, 2021, which gives users a grace period of almost 2 years up to next release of Kafka for JUnit, which will be version 3.3.0.

The following classes are affected:

* `EmbeddedZooKeeperConfig`
* `EmbeddedConnectConfig`
* `EmbeddedKafkaClusterConfig`
* `EmbeddedKafkaConfig`
* `LeaderAndIsr`
* `TopicConfig`

It is not necessary to update the user's guide, as the documentation already reflects the preferred way to configure the embedded cluster.

**Acceptance criteria:**

* All methods that are annotated with `@Deprecated` have been removed from the aformentioned classes.
* All tests are still running.

### 📋 Step by Step

To solve this issue and contribute a fix you should check the following step-by-step list. A more detailed documentation of the workflow can be found [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).

- [ ] Claim this issue: Comment below.
- [ ]  Fork the repository in github by simply clicking the 'fork' button.
- [ ]  Check out the forked repository
- [ ]  Create a feature branch for the issue. There are no enforced naming conventions for branches. In the past, we simply used `issue-XX`, `XX` being the number of the issue you are working on.
- [ ]  Commit your changes.
- [ ]  Start a Pull Request.
- [ ]  Done 👍 Ask in comments for a review :)
- [ ]  If the reviewer find some missing pieces or a problem he will start a discussion with you and describe the next steps how the problem can be solved.
- [ ]  You did it 🎉 We will merge the fix in the development branch.
- [ ]  Thanks, thanks, thanks for being part of this project as an open source contributor ❤️

### 🎉 Contribute to Hacktoberfest

Solve this issue as part of the [Hacktoberfest](https://hacktoberfest.digitalocean.com) event and get a change to receive cool goodies like a T-Shirt. 🎽

### 🤔❓ Questions

If you have any questions just ask us directly in this issue by adding a comment.

**Comment by keer-0** [comment]
Hi @mguenther ,
can I pick this up ? If yes, do assign me to this issue

**Comment by mguenther** [comment]
I appreciate the interest and support! I'm reserving a couple of tickets for the [Cyberland Open Source Camp](https://cyberland.ijug.eu/2022-10-open-source-camp/) for newcomers to OSS contributions - I'll be mentoring there tomorrow. If no one will pick it up as part of that session, I'd be happy to assign you.

**Comment by ghajba** [comment]
Hello Markus @mguenther, I'd like to tackle this task.

**Comment by mguenther** [comment]
Hi @ghajba ! Thanks for your interest! I've assigned this issue to you (as part of the Cyberland Open Source Camp). Happy hacking!

**Comment by mguenther** [comment]
Fix has been merged. Thanks a lot, @ghajba!
