### ISSUE TITLE
Fix deprecated API usage in class `DefaultTopicManager`

### ISSUE THREAD

**Issue by mguenther** [mguenther/kafka-junit#76]
### 🆕🐥 First Timers Only

This issue is reserved for people who never contributed to Open Source before. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

### 👾 Description of the issue

`DefaultTopicManager.fetchLeaderAndIsr` utilizes `DescribeTopicsResult.all` to fetch information about all topics that the cluster manages. `DescribeTopicsResult.all` has been deprecated a couple of releases back and we should adjust our client code as appropriate. Follow the migration guideline provided by the Javadoc of `DescribeTopicsResult.all`.

**Acceptance criteria:**

* `DefaultTopicManager` no longer exhibits any deprecation warnings.
* All tests are still running.

### 📋 Step by Step

To solve this issue and contribute a fix you should check the following step-by-step list. A more detailed documentation of the workflow can be found [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).

- [ ] Claim this issue: Comment below.
- [ ]  Fork the repository in github by simply clicking the 'fork' button.
- [ ]  Check out the forked repository
- [ ]  Create a feature branch for the issue. There are no enforced naming conventions for branches. In the past, we simply used `issue-XX`, `XX` being the number of the issue you are working on.
- [ ]  Commit your changes.
- [ ]  Start a Pull Request.
- [ ]  Done 👍 Ask in comments for a review :)
- [ ]  If the reviewer find some missing pieces or a problem he will start a discussion with you and describe the next steps how the problem can be solved.
- [ ]  You did it 🎉 We will merge the fix in the development branch.
- [ ]  Thanks, thanks, thanks for being part of this project as an open source contributor ❤️

### 🎉 Contribute to Hacktoberfest

Solve this issue as part of the [Hacktoberfest](https://hacktoberfest.digitalocean.com) event and get a change to receive cool goodies like a T-Shirt. 🎽

### 🤔❓ Questions

If you have any questions just ask us directly in this issue by adding a comment.

**Comment by anuragh2002** [comment]
Hey @mguenther I would like to work on this issue. Can you please guide me through my first contribution? I am an intermediate in Java.

**Comment by mguenther** [comment]
I appreciate the interest and support! I'm reserving a couple of tickets for the [Cyberland Open Source Camp](https://cyberland.ijug.eu/2022-10-open-source-camp/) for newcomers to OSS contributions - I'll be mentoring there tomorrow. If no one will pick it up as part of that session, I'd be happy to assign you.

**Comment by JOpsDev** [comment]
Hi from the CyberLand #Hacktoberfest event. I'd like to contribute here.

**Comment by mguenther** [comment]
Thank you very much for your contribution, @JOpsDev. Enjoy the rest of #hacktoberfest!
