### ISSUE TITLE
Fix deprecated API usage in class `ExternalKafkaClusterTest`

### ISSUE THREAD

**Issue by mguenther** [mguenther/kafka-junit#78]
### 🆕🐥 First Timers Only

This issue is reserved for people who never contributed to Open Source before. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

### 👾 Description of the issue

The test class `ExternalKafkaClusterTest` uses `KafkaContainer` from Testcontainers to spin up an external cluster that we can attach to. The no-args constructor of `KafkaContainer` is deprecated and we should move to `KafkaContainer(DockerImageName)`. The `DockerImageName` should reflect the default of Testcontainers though, which is:
* name: confluentinc/cp-kafka
* tag: 5.4.3

**Acceptance criteria:**

* `ExternalKafkaClusterTest` no longer exhibits any deprecation warnings.
* All tests are still running.

### 📋 Step by Step

To solve this issue and contribute a fix you should check the following step-by-step list. A more detailed documentation of the workflow can be found [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).

- [ ] Claim this issue: Comment below.
- [ ]  Fork the repository in github by simply clicking the 'fork' button.
- [ ]  Check out the forked repository
- [ ]  Create a feature branch for the issue. There are no enforced naming conventions for branches. In the past, we simply used `issue-XX`, `XX` being the number of the issue you are working on.
- [ ]  Commit your changes.
- [ ]  Start a Pull Request.
- [ ]  Done 👍 Ask in comments for a review :)
- [ ]  If the reviewer find some missing pieces or a problem he will start a discussion with you and describe the next steps how the problem can be solved.
- [ ]  You did it 🎉 We will merge the fix in the development branch.
- [ ]  Thanks, thanks, thanks for being part of this project as an open source contributor ❤️

### 🎉 Contribute to Hacktoberfest

Solve this issue as part of the [Hacktoberfest](https://hacktoberfest.digitalocean.com) event and get a change to receive cool goodies like a T-Shirt. 🎽

### 🤔❓ Questions

If you have any questions just ask us directly in this issue by adding a comment.

**Comment by mslowiak** [comment]
Hi @mguenther! 
Can I pick it up? I would like to work on it in the next week during hacktoberfest

**Comment by mguenther** [comment]
Hi @mslowiak ! Absolutely, go ahead and assign the issue to yourself. Appreciate your help!

**Comment by mslowiak** [comment]
@mguenther You are the owner of the repo, so you need to assign me there :D

**Comment by mguenther** [comment]
Thank you very much @mslowiak for your contribution! Enjoy the rest of Hacktoberfest!
