### ISSUE TITLE
Remove usage of yet unsupported Java >8 language features

### ISSUE THREAD

**Issue by mguenther** [mguenther/kafka-junit#86]
This only affects `EmbeddedConnect`. The code in question is this:

```
private static Supplier<TopicAdmin> getTopicAdminSupplier(String brokerList) {
  return () -> new TopicAdmin(Map.of(WorkerConfig.BOOTSTRAP_SERVERS_CONFIG, brokerList));
}
```

which unfortunately got merged without taking care of this beforehand (original issue: #77).

**Comment by mguenther** [comment]
Fix merged into `development`.

**Comment by ghajba** [comment]
Sorry for introducing this bug. I have found the culprit and updated my local env to use only Java <= 8 features.

**Comment by mguenther** [comment]
No worries! It's taken care of. :)
