### ISSUE TITLE
Copy-Paste Sample Code in Docs Not Working

### ISSUE THREAD

**Issue by matthewparks-rts** [mguenther/kafka-junit#96]
I'm trying out this library and struggling to get it working. I'm having a hard time determining if I'm using it wrong, or if there's an actual bug/issue in the library. (I'm using v 3.4.0)

Here's from the Readme:

```java
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static net.mguenther.kafka.junit.EmbeddedKafkaCluster.provisionWith;
import static net.mguenther.kafka.junit.EmbeddedKafkaClusterConfig.defaultClusterConfig;

class KafkaTest {

    private EmbeddedKafkaCluster kafka;

    @BeforeEach
    void setupKafka() {
        kafka = provisionWith(defaultClusterConfig());
        kafka.start();
    }

    @AfterEach
    void tearDownKafka() {
        kafka.stop();
    }

    @Test
    void shouldWaitForRecordsToBePublished() throws Exception {
        kafka.send(to("test-topic", "a", "b", "c"));
        kafka.observe(on("test-topic", 3));
    }
}
```

When I copy and paste it into a class, there's a few issues.

1. It's missing imports. I needed to add the following:

import net.mguenther.kafka.junit.EmbeddedKafkaCluster;
import static net.mguenther.kafka.junit.ObserveKeyValues.on;
import static net.mguenther.kafka.junit.SendValues.to;

2. When I attempt to run this test, I get the following error:

> Topic test-topic not present in metadata after 60000 ms.
> org.apache.kafka.common.errors.TimeoutException: Topic test-topic not present in metadata after 60000 ms.

3. I attempted to add the topic [per section 7.1](https://mguenther.github.io/kafka-junit/#_creating_a_topic) of the docs as follows:

```java
  @Test
    void shouldWaitForRecordsToBePublished() throws Exception {
        //Note, this requires adding import net.mguenther.kafka.junit.TopicConfig; above
        kafka.createTopic(TopicConfig.withName("test-topic"));
        kafka.send(to("test-topic", "a", "b", "c"));
        kafka.observe(on("test-topic", 3));
    }
```

When I re-ran the test, I get the following error:

> A timeout occurred while trying to create topic 'test-topic'.
> java.lang.RuntimeException: A timeout occurred while trying to create topic 'test-topic'.

I'll mention that while the test is running, I do see my port 9092 getting used, so that much seems to be successful.

I'm not sure what to do next. If I can't get the code from the documentation itself to work, it seems unlikely I'll be able to get it working for testing my code. Thank you!

**Comment by mguenther** [comment]
Thanks for bringing this to my attention! You're absolutely right: The documentation is lacking the necessary imports, and I'll address this shortly.

In my attempt to reproduce the effects that you're observing, I created a new Maven project based on the `maven-archetype-quickstart` archetype, and added the following dependencies:

```xml
    <dependencies>
        <dependency>
            <groupId>net.mguenther.kafka</groupId>
            <artifactId>kafka-junit</artifactId>
            <version>3.4.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>5.8.2</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <version>5.8.2</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>1.7.35</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
```

I then created the following test class.

```java
package org.example;

import net.mguenther.kafka.junit.EmbeddedKafkaCluster;
import net.mguenther.kafka.junit.EmbeddedKafkaClusterConfig;
import net.mguenther.kafka.junit.ObserveKeyValues;
import net.mguenther.kafka.junit.SendValues;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

class KafkaTest {

    private EmbeddedKafkaCluster kafka;

    @BeforeEach
    void setupKafka() {
        kafka = EmbeddedKafkaCluster.provisionWith(EmbeddedKafkaClusterConfig.defaultClusterConfig());
        kafka.start();
    }

    @AfterEach
    void tearDownKafka() {
        kafka.stop();
    }

    @Test
    void shouldWaitForRecordsToBePublished() throws Exception {
        kafka.send(SendValues.to("test-topic", "a", "b", "c"));
        kafka.observe(ObserveKeyValues.on("test-topic", 3));
    }
}
```

This is the exact test case that the `README.md` shows (well, without the static imports). It runs through just fine.

If you're using an `EmbeddedKafka` broker, then automatic topic creation is activated by default. Creating a topic explicitly should not be necessary.

I'm not sure what's causing this behavior on your end. I can't think of any connectivity issues (like the output you showed may suggest), unless the broker does not start up at all - which, as you said, does in fact happen.

**Comment by mguenther** [comment]
What OS are you running on?

**Comment by mguenther** [comment]
Here's my example project. Please go ahead and try it out yourself.

[kafka-junit-issue-96-test.zip](https://github.com/mguenther/kafka-junit/files/11971269/kafka-junit-issue-96-test.zip)

**Comment by matthewparks-rts** [comment]
Thank you!

I'm running on Ubuntu 22.04.2 LTS.

I downloaded your zip and happily, it works for me just fine. So what's different between that and my project is the question. I'm not seeing much except that I'm using gradle instead of maven, and those appear to be similar as to what they're doing, though I'll look at it more closely in a minute.

What I have noticed is the difference in usages of port 9092 between when I run the test in my project vs your zipped project. I don't know why the difference or what it might mean. Perhaps the broker(s) are not starting up correctly or sufficiently or something? Yeah, ignorance on my part, here. :-) 

When Running My Project:
```bash
$ sudo lsof -i -P -n | grep 9092
java      1564792         matthew  211u  IPv6 54161801      0t0  TCP 127.0.0.1:9092 (LISTEN)
java      1564792         matthew  224u  IPv6 54168622      0t0  TCP 127.0.0.1:49762->127.0.0.1:9092 (ESTABLISHED)
java      1564792         matthew  225u  IPv6 54134554      0t0  TCP 127.0.0.1:9092->127.0.0.1:49762 (ESTABLISHED)
```

When Running Your Sample Project:
```bash
$ sudo lsof -i -P -n | grep 9092
java      1563348         matthew  141u  IPv6 54120016      0t0  TCP 127.0.0.1:9092 (LISTEN)
java      1563348         matthew  154u  IPv6 54117262      0t0  TCP 127.0.0.1:36308->127.0.0.1:9092 (ESTABLISHED)
java      1563348         matthew  155u  IPv6 54118557      0t0  TCP 127.0.0.1:9092->127.0.0.1:36308 (ESTABLISHED)
java      1563348         matthew  158u  IPv6 54117263      0t0  TCP 127.0.0.1:36334->127.0.0.1:9092 (ESTABLISHED)
java      1563348         matthew  159u  IPv6 54118561      0t0  TCP 127.0.0.1:9092->127.0.0.1:36334 (ESTABLISHED)
java      1563348         matthew  160u  IPv6 54115287      0t0  TCP 127.0.0.1:36322->127.0.0.1:9092 (ESTABLISHED)
java      1563348         matthew  161u  IPv6 54118559      0t0  TCP 127.0.0.1:9092->127.0.0.1:36322 (ESTABLISHED)
java      1563348         matthew  163u  IPv6 54117264      0t0  TCP 127.0.0.1:36340->127.0.0.1:9092 (ESTABLISHED)
java      1563348         matthew  164u  IPv6 54120516      0t0  TCP 127.0.0.1:9092->127.0.0.1:36340 (ESTABLISHED)
```

**Comment by mguenther** [comment]
It's perfectly fine to see multiple (established) connections when running these tests. Kafka for JUnit constructs new consumers all the time (to ensure that nothing - as in: consumer offsets and such - get in the way when you observe a topic or read from the topic multiple times as part of a test case). So, what you see in the second output of `lsof` is to be expected.

Personally, I don't use Gradle all that much. One of my customers uses a Gradle-based build as well as Kafka for JUnit for testing Kafka components. I haven't heard of any issues with Gradle in combination with Kafka for JUnit. I can't think of any side effects that a build tool might introduce that would trigger that kind of behavior.

I don't think this is a bug per se. If you happen to stumble upon any other differences between the two project setups, please let me know.

**Comment by matthewparks-rts** [comment]
Yeah, not sure what's going on here. I'd suggest closing this out as an issue. If I do figure out what's going on, I'll add a comment here and let you know. Thanks again!
