### ISSUE TITLE
Apache Kafka 3.5.x Support?

### ISSUE THREAD

**Issue by locomark** [mguenther/kafka-junit#97]
It looks like there were some considerable breaking changes with version 3.5.0 release.  
Any plan/timeline to address with an update?  
Looks like more connect changes in particular...
Great library btw!

**Comment by mguenther** [comment]
Hi! Thanks for the kind words!

There is no timeline yet. It will take a couple of weeks before I am able to take a look at the version upgrade.

**Comment by mguenther** [comment]
Dependencies have been upgraded to Kafka 3.5.1. This will be included in release 3.5.0 of Kafka for JUnit.
